### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Farang1969** [Greentube/ngx-modal#1]
Cannot find module '@greentube/ngx-modal'

import { ModalDialogModule } from '@greentube/ngx-modal';

It simply says:

Module not found: Error: Can't resolve '@greentube/ngx-modal' in 'C:\Data\Centric\Angular4\test-app\src\app'

**Comment by meeroslav** [comment]
@Farang1969 There is an error in the documentation.

Use `ngx-modal-dialog` instead of `@greentube/ngx-modal`.
