### ISSUE TITLE
Data information for simple modal dialog is missing

### ISSUE THREAD

**Issue by TheGodFather05** [Greentube/ngx-modal#14]
this is the message i get while trying to use the SimpleModalDialog as child component

**Comment by meeroslav** [comment]
Hi @TheGodFather05 , `SimpleModalDialog` requires you to pass a `data` object with `text` field.

Please have a look at the source code on demo here: [https://github.com/Greentube/ngx-modal/blob/master/demo/src/app/app.component.ts#L30-L32](https://github.com/Greentube/ngx-modal/blob/master/demo/src/app/app.component.ts#L30-L32)
