### ISSUE TITLE
Returning data from modal to parent component

### ISSUE THREAD

**Issue by vethencourt** [Greentube/ngx-modal#16]
I'm not sure if this is possible with this package, and please let me know if its not, but I want to open an object in a modal, modify it, and update the object in the parent component with said modifications. 

I have this button in the Modal Component:
`{ text: 'Save', onAction: () => this.saveDealer() }`

The function called (sorry for the mess I have no idea how this Github editor works):

`    saveDealer(): Observable<any> {
      let subject = new Subject<any>();
      subject.next(this.dealer);
      return subject.asObservable();
    }
`

The function that opens the modal from the parent component:
`  edit(dealer) {
    this.modalService.openDialog(this.viewRef, {
      title: 'Editar',
      childComponent: EditConcesionarioComponent,
      settings: { contentClass: "modal-content modal-width" },
      data: dealer,
      onClose: () => ?? //I'm guessing this is where the return is supposed to happen 
    });
  }`

**Comment by Sayan751** [comment]
This can be done using `options.closeDialogSubject` in `openDialog`. Example:

```typescript
// parent component or subscriber

const dialogOptions = {
  // other options are removed for brevity
  closeDialogSubject: new Subject<any>()
};

// subscribe to event
dialogOptions.closeDialogSubject.subscribe({
  next: (data) => {
    console.log("#2 Dialog closed and notified in the list via subscription, data rcvd -->", data);
  }
});
this.modalService.openDialog(this.viewRef, dialogOptions);

/*-----------------------------*/

// inside dialog or publisher

export class MyDialogComponent implements IModalDialog {

  public data: any;
  public actionButtons: IModalDialogButton[];
  private closeDialogSubject: Subject<void>;

  constructor() {
    this.actionButtons = [
      { text: "Save",  onAction: () => { this.saveChanges(); } },
      { text: "Close" },
    ];
  }
  dialogInit(reference: ComponentRef<IModalDialog>, options: Partial<IModalDialogOptions<any>>) {
    this.data= options.data;
    this.closeDialogSubject = options.closeDialogSubject;
  }

  saveChanges(): any {
    this.closeDialogSubject.next(this.data); // publish data
  }
}
```

This should be a viable solution. However, there seems to be following two problems, for which this is not working at this moment.

1. `options.closeDialogSubject` from the subscriber is replaced in [`ModalDialogComponent#dialogInit`](https://github.com/Greentube/ngx-modal/blob/master/src/modal-dialog.component.ts#L146-L151). This means that the original subscriber will never be notified.
2. The type of [`IModalDialogOptions<T>#closeDialogSubject`](https://github.com/Greentube/ngx-modal/blob/master/src/modal-dialog.interface.ts#L16) is `Subject<void>`, which causes following TypeScript compilation error on `this.closeDialogSubject.next(this.data);`:
> Argument of type 'MyType' is not assignable to parameter of type 'void'

Are you interested in aaccepting PRs?

**Comment by meeroslav** [comment]
Hi @vethencourt,

There are two ways you can pass information back to parent:
- mutable
- immutable

**Mutable approach** would be to pass some object to modal dialog options, change this object inside the dialog and have the change immediately in your parent. Though, this solution is simple, it's not recommended as it might lead to unplanned side-effects if not used carefully.

**Immutable approach** would be to pass either a Subject or EventEmitter via `options` - similarly to proposal by @Sayan751, and then on save just call subject.next(yourData) or eventEmitter.emit(yourData). All you need to do on your parent, is to subscribe to subject/event changes.

**Comment by kdekooter** [comment]
@meeroslav could you please provide us with a sample of the immutable approach with a `Subject`? Burning precious trial-and-error time here.

**Comment by kdekooter** [comment]
@meeroslav I am "just" calling `subject.next()` but my original observer is never triggered

Parent code:
```ts
popupContextSelection() {

  let closeDialogSubject = new Subject<any>();

  closeDialogSubject.subscribe((data) => {
      console.log(data)
    }
  );

  this.modalService.openDialog(this.viewRef, {
    title: 'Select Contexts',
    childComponent: EntitySelectionComponent,
    data: { entities: this.contexts },
    closeDialogSubject: closeDialogSubject,
  })
}
```

Modal code:
```
export class EntitySelectionComponent implements OnInit, IModalDialog {

  actionButtons: IModalDialogButton[];
  entities: any[];
  selected: number[] = [];
  private closeDialogSubject: Subject<any>;

  constructor() {
    this.actionButtons = [
      {text: 'Cancel', buttonClass: 'cms-button'},
      {text: 'Select', buttonClass: 'cms-button-primary', onAction: () => { this.saveSelectedItems() }}
    ]
  }

  dialogInit(reference: ComponentRef<IModalDialog>,
             options: Partial<IModalDialogOptions<string>>) {
    this.entities = options.data['entities'];
    this.closeDialogSubject = options.closeDialogSubject
  }

  saveSelectedItems() {
    this.closeDialogSubject.next('boo');
  }
}
```
