### ISSUE TITLE
How to use IModalDialogSettings

### ISSUE THREAD

**Issue by MansoorJafari** [Greentube/ngx-modal#18]
Hello
 how to set 'modal-lg' class to modal class?

Thanks.

**Comment by bserranocima** [comment]
Hi. In your dialog options set as following:

`this.modalService.openDialog(this.viewRef, {
settings: { modalClass: 'your-class'  }
}); `

**Comment by MansoorJafari** [comment]
Thanks  for your answer
I change my code 
`
  this.modalService.openDialog(this.viewRef, {settings: { modalDialogClass: 'modal-lg' },
    title: 'Some modal title',
    childComponent: CustomerTestAccountComponent
  });

`
but 'modal-lg' class not work.

**Comment by meeroslav** [comment]
@MansoorJafari, for animation you can use `overlayAnimationTriggerClass` and `modalAnimationTriggerClass` in `IModalDialogSettings`.
