### ISSUE TITLE
Closing modal when click outside the modal-dialog

### ISSUE THREAD

**Issue by yarostbaklajana** [Greentube/ngx-modal#19]
Hello,

Is there any possibility to close modal by clicking on the backdrop?

Thank you in advance)

**Comment by meeroslav** [comment]
Hi @yarostbaklajana, modal dialog can be closed by clicking on the backdrop only in case when there are no action buttons defined.

Otherwise it would not know which action to perform on backdrop clicking.

**Comment by btargac** [comment]
Hi @yarostbaklajana could you make it work by not defining any action buttons?

**Comment by btargac** [comment]
@meeroslav thanks for the fix, but this way when you click inside the modal it also disapears. At leat in my setup when i click in the modal area it suddenly closed.
