### ISSUE TITLE
Cannot find name 'ModalDialogService'

### ISSUE THREAD

**Issue by Farang1969** [Greentube/ngx-modal#2]
The constructor won't work:

constructor(modalService: ModalDialogService, viewRef: ViewContainerRef)

It does not know of ModalDialogService.

Can you please make a complete working example, or tell me where how to declare ModalDialogService?

Thanks

**Comment by meeroslav** [comment]
Hi @Farang1969 ,

`ModalDialogService` is part of `ngx-modal-dialog`, so you include it with:
```ts
import { ModalDialogService } from 'ngx-modal-dialog';
```

We are still working on a demo site where you can see different options of modal-dialog. At the moment you can look at [https://github.com/meeroslav/angular2-seed](https://github.com/meeroslav/angular2-seed). It has an example of simple modal usage. If you need any help on advanced setup of modal dialog please feel free to ping us here.
