### ISSUE TITLE
close modal

### ISSUE THREAD

**Issue by MansoorJafari** [Greentube/ngx-modal#20]
Hello
my form has submit button 
how can I set submit for to modal button with ngform input
like this
`      <form #f="ngForm" (ngSubmit)="createAccount(f)">
`

**Comment by meeroslav** [comment]
I propose to use [ReactiveForms](https://angular.io/guide/reactive-forms). This makes the whole flow of form data more code driven.

If you insist to use `ngForm` directive you can access your form using:

```ts
// here we grab the ref to our form
@ViewChild('f') myForm;

//... this is inside `dialogInit` method
options.actionButtons = [{
  text: 'Submit...',
  onAction: () => {
    // now we can pass it to create account
    this.createAccount(this.myForm);
    // in order to close dialog we need to return 'truthful' response 
    return true;
  }
}];
```
