### ISSUE TITLE
Dynamic set of actionButtons

### ISSUE THREAD

**Issue by vtcaregorodtcev** [Greentube/ngx-modal#22]
Hi, looks like we can't now reset count of actionButtons on modal window component or rename some of them depends on some variable. 

something like this:

```
constructor() {
  this.actionButtons = [
    { text: 'Toggle', onAction: () => this.actionButtons.concat({
       text: 'NewOne', onAction: () => true
    }) },
    { text: 'Cancel', onAction: () => true },
    { text: 'Save', onAction: () => true }
  ];
}

```

**Comment by meeroslav** [comment]
Please check the latest demo at [https://greentube.github.io/ngx-modal/](https://greentube.github.io/ngx-modal/). I believe that is what you are looking for.

Action buttons are part of parent `ModalDialogComponent`, but on the method `dialogInit` they are passed as part of options object, so you can still modify them or grab a reference to them for later changes.
