### ISSUE TITLE
Set IModalOption.data and send it back to parent

### ISSUE THREAD

**Issue by iamnilay3** [Greentube/ngx-modal#24]
Hi,

how could I set the IModalOption.data  from a server call in async way and send it back from modal to parent.

**Comment by meeroslav** [comment]
If you are using mutable structure you could do this.

```typescript

myMutableObject = {
  innerData: 'some value'
};

this.modalService.openDialog(this.viewRef, {
    title: 'Some title',
    childComponent: SomeComponent,
    data: myMutableObject
});

```

And then have in your `SomeComponent` (modal dialog component) piece of code like this:

```typescript
this.myService.getSomeData(data => {
   // if you only mutate the inner property your parent component will change as well
   this.data.innerData = data;
});
```

However, I would not suggest to do this. Instead I would do let child modal component just trigger async method on parent component. Check #21
