### ISSUE TITLE
how to call a new modal inside a childcomponent?

### ISSUE THREAD

**Issue by donking13** [Greentube/ngx-modal#28]
when I call a new modal from the childcomponent, it just exits the model and show nothing.

how should I do this?

**Comment by meeroslav** [comment]
Not sure I follow. Are you trying to open modal dialog from within another modal dialog?

If yes, then answer is unfortunately that this is not yet implemented.

**Comment by donking13** [comment]
Hi meeroslav,  I was able to make it work with observables. I think I also prefer is this way.
