### ISSUE TITLE
SimpleModalComponent closes immediatly after button click

### ISSUE THREAD

**Issue by userAbhi** [Greentube/ngx-modal#31]
I am using angular 4 and trying to open a SimpleModalComponent on button click as per Readme file provided. But the popup came and immediately disappears. Next time when I clicked on my open popup button it first calls close method of popup and after another click same happens that I mention above.

**Comment by MSandeep111** [comment]
Please check the bootstrap version what you are using on your index.html is should be >=4.X.X.
I am having the same issue by changing the version it works like a charm.
