### ISSUE TITLE
Manually close

### ISSUE THREAD

**Issue by LuisUrrutia** [Greentube/ngx-modal#4]
How can i close the modal manually? I saw that there is an close() function, but i don't know how to call it.

**Comment by joaopgrassi** [comment]
@LuisUrrutia not sure if I understood you correctly. You want to close the modal somewhere else on your code? Can you elaborate more on your example?

**Comment by LuisUrrutia** [comment]
Yeah, I have this:

```
import { Component, ComponentRef, ViewEncapsulation } from '@angular/core';
import { IModalDialog, IModalDialogOptions } from 'ngx-modal-dialog';
import { Institution } from '../../_models/Institution';
import { InstitutionService } from '../../_services/institution.service';

@Component({
  selector: 'new-institution',
  styleUrls: [ './new.component.scss' ],
  templateUrl: 'new.component.html',
  encapsulation: ViewEncapsulation.None
})
export class NewInstitutionComponent implements IModalDialog {
  public institution: Institution;

  private reference: ComponentRef<IModalDialog>;
  private institutionService: InstitutionService;

  constructor(institutionService: InstitutionService) {
    this.institutionService = institutionService;
  }

  public dialogInit(reference: ComponentRef<IModalDialog>, options?: IModalDialogOptions) {
    this.reference = reference;
    this.institution = new Institution();
  };

  public onCreate() {
    // here, i want to close the modal
  }
}
```

That is the component that is opened like a modal, and "onCreate" is a method that is executed after a click in a button, and i don't want to use "actionButtons" 'cause the button that i created has custom directives.

**Comment by joaopgrassi** [comment]
Currently this behavior is not yet implemented. We will work on a solution and you can expect this in the new version. Thank you for the input.

**Comment by giordanni612** [comment]
Hi, there.
I'm dealing with this issue. When I call close() fucntion in my custom method, the console shows the following warning: "Scripts may not close windows that were not opened by script." I'm using Angular 6

**Comment by giordanni612** [comment]
Hi, there.
I'm dealing with this issue. When I call close() fucntion in my custom method, the console shows the following warning: "Scripts may not close windows that were not opened by script." I'm using Angular 6
