### ISSUE TITLE
Custom action doesn't handle response from Promise/Observable

### ISSUE THREAD

**Issue by szilardd** [Greentube/ngx-modal#7]
When providing a custom callback to an action and if the response is a Promise/Observable, the result is not used to check whether the modal needs to be closed or not, it is always closed no matter what the response is.

https://github.com/Greentube/ngx-modal/blob/master/src/modal-dialog.component.ts#L248-L252

Shouldn't be something like this ?

`response.subscribe((result) => {`
   `	   if (result) {`
`		this._finalizeAndDestroy();`
`	} else {`
`		this._inProgress = false;`
`	}`
`}, () => {`
`        this._inProgress = false;`
`	this._triggerAlert();`
`});`

Thanks for your effort!

**Comment by meeroslav** [comment]
@szilardd, actually no.

The idea is: 
* if your Promise is resolved or Observable was successful, close the dialog
* if your Promise was rejected or Observable failed, alert user and remain on the dialog

The reasoning behind is that most common scenario is to call put/post/delete method on an API. We generally don't care about the response if it's successful (response is often without body).

If you need to handle the response, you can wrap it in another Promise or Observable that would fail/succeed depending on the response.
